CREATE LOGIN [CanListen] WITH PASSWORD = 'SQL2024'

CREATE LOGIN[CanCreatePlayslist] WITH PASSWORD = 'SQL2024U'

CREATE LOGIN [SeeDataMaskedUser] WITH PASSWORD ='SQL2024UD'




ALTER TABLE Users  ALTER COLUMN  UserName ADD MASKED WITH ( FUNCTION ='default()');

ALTER TABLE Users  ALTER COLUMN Email ADD MASKED WITH (FUNCTION ='Email()');

SELECT * FROM Users

GRANT UNMASK  to SeeDataMaskedUser;

BACKUP DATABASE [MusicStreaming1] TO DISK  = 'C:\BackUp_SQL\MusicStreaming1.BAK'